apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}
spec:
  capacity:
    storage: {{ .Values.volumeClaimTemplates.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
   path: /var/lib/nginx/data
   type: DirectoryOrCreate
 